module.exports = [

/* ======================= WICKET KEEPERS (40) ======================= */
{name:"MS Dhoni",role:"WK",rating:9.4,foreign:false},
{name:"KL Rahul",role:"WK",rating:8.9,foreign:false},
{name:"Rishabh Pant",role:"WK",rating:8.8,foreign:false},
{name:"Sanju Samson",role:"WK",rating:8.7,foreign:false},
{name:"Ishan Kishan",role:"WK",rating:8.6,foreign:false},
{name:"Jitesh Sharma",role:"WK",rating:7.9,foreign:false},
{name:"KS Bharat",role:"WK",rating:7.6,foreign:false},
{name:"Dhruv Jurel",role:"WK",rating:7.8,foreign:false},
{name:"Prabhsimran Singh",role:"WK",rating:7.7,foreign:false},
{name:"Ricky Bhui",role:"WK",rating:7.4,foreign:false},

{name:"Jos Buttler",role:"WK",rating:9.6,foreign:true},
{name:"Quinton de Kock",role:"WK",rating:9.1,foreign:true},
{name:"Jonny Bairstow",role:"WK",rating:8.9,foreign:true},
{name:"Nicholas Pooran",role:"WK",rating:9.2,foreign:true},
{name:"Heinrich Klaasen",role:"WK",rating:9.3,foreign:true},
{name:"Tim Seifert",role:"WK",rating:8.0,foreign:true},
{name:"Phil Salt",role:"WK",rating:8.2,foreign:true},
{name:"Matthew Wade",role:"WK",rating:8.1,foreign:true},
{name:"Alex Carey",role:"WK",rating:8.3,foreign:true},
{name:"Tom Latham",role:"WK",rating:8.4,foreign:true},

{name:"Rahmanullah Gurbaz",role:"WK",rating:8.5,foreign:true},
{name:"Kusal Mendis",role:"WK",rating:8.2,foreign:true},
{name:"Dinesh Chandimal",role:"WK",rating:8.0,foreign:true},
{name:"Mohammad Rizwan",role:"WK",rating:9.0,foreign:true},
{name:"Sarfaraz Ahmed",role:"WK",rating:7.8,foreign:true},
{name:"Litton Das",role:"WK",rating:8.1,foreign:true},
{name:"Shai Hope",role:"WK",rating:8.3,foreign:true},
{name:"Andre Fletcher",role:"WK",rating:7.6,foreign:true},
{name:"Kyle Verreynne",role:"WK",rating:7.9,foreign:true},
{name:"Ben McDermott",role:"WK",rating:8.0,foreign:true},

/* ======================= BATSMEN (40) ======================= */
{name:"Virat Kohli",role:"BAT",rating:9.7,foreign:false},
{name:"Rohit Sharma",role:"BAT",rating:9.3,foreign:false},
{name:"Shubman Gill",role:"BAT",rating:9.4,foreign:false},
{name:"Suryakumar Yadav",role:"BAT",rating:9.5,foreign:false},
{name:"Shreyas Iyer",role:"BAT",rating:8.6,foreign:false},
{name:"Yashasvi Jaiswal",role:"BAT",rating:9.2,foreign:false},
{name:"Ruturaj Gaikwad",role:"BAT",rating:8.9,foreign:false},
{name:"Tilak Varma",role:"BAT",rating:8.4,foreign:false},
{name:"Devdutt Padikkal",role:"BAT",rating:8.2,foreign:false},
{name:"Abhishek Sharma",role:"BAT",rating:8.3,foreign:false},

{name:"Prithvi Shaw",role:"BAT",rating:8.0,foreign:false},
{name:"Mayank Agarwal",role:"BAT",rating:8.1,foreign:false},
{name:"Manish Pandey",role:"BAT",rating:7.8,foreign:false},
{name:"Ajinkya Rahane",role:"BAT",rating:8.0,foreign:false},
{name:"Karun Nair",role:"BAT",rating:7.6,foreign:false},
{name:"Sai Sudharsan",role:"BAT",rating:8.5,foreign:false},
{name:"Rahul Tripathi",role:"BAT",rating:8.4,foreign:false},
{name:"Shivam Mavi",role:"BAT",rating:7.2,foreign:false},
{name:"Sarfaraz Khan",role:"BAT",rating:8.3,foreign:false},
{name:"Abdul Samad",role:"BAT",rating:7.9,foreign:false},

{name:"David Warner",role:"BAT",rating:9.1,foreign:true},
{name:"Faf du Plessis",role:"BAT",rating:9.0,foreign:true},
{name:"Steve Smith",role:"BAT",rating:8.7,foreign:true},
{name:"Kane Williamson",role:"BAT",rating:8.9,foreign:true},
{name:"Babar Azam",role:"BAT",rating:9.6,foreign:true},
{name:"Joe Root",role:"BAT",rating:9.2,foreign:true},
{name:"Glenn Phillips",role:"BAT",rating:8.5,foreign:true},
{name:"Aiden Markram",role:"BAT",rating:8.6,foreign:true},
{name:"Rilee Rossouw",role:"BAT",rating:8.4,foreign:true},
{name:"Harry Brook",role:"BAT",rating:8.7,foreign:true},

/* ======================= ALL ROUNDERS (30) ======================= */
{name:"Hardik Pandya",role:"ALL",rating:9.1,foreign:false},
{name:"Ravindra Jadeja",role:"ALL",rating:9.3,foreign:false},
{name:"Axar Patel",role:"ALL",rating:8.7,foreign:false},
{name:"Shivam Dube",role:"ALL",rating:8.3,foreign:false},
{name:"Washington Sundar",role:"ALL",rating:8.4,foreign:false},
{name:"Krunal Pandya",role:"ALL",rating:8.2,foreign:false},
{name:"Nitish Kumar Reddy",role:"ALL",rating:7.9,foreign:false},
{name:"Vijay Shankar",role:"ALL",rating:7.8,foreign:false},
{name:"Deepak Hooda",role:"ALL",rating:8.1,foreign:false},
{name:"Shardul Thakur",role:"ALL",rating:8.5,foreign:false},

{name:"Andre Russell",role:"ALL",rating:9.6,foreign:true},
{name:"Marcus Stoinis",role:"ALL",rating:8.9,foreign:true},
{name:"Sam Curran",role:"ALL",rating:8.8,foreign:true},
{name:"Wanindu Hasaranga",role:"ALL",rating:9.2,foreign:true},
{name:"Sunil Narine",role:"ALL",rating:9.0,foreign:true},
{name:"Mitchell Marsh",role:"ALL",rating:8.7,foreign:true},
{name:"Cameron Green",role:"ALL",rating:8.9,foreign:true},
{name:"Jason Holder",role:"ALL",rating:8.6,foreign:true},
{name:"Moises Henriques",role:"ALL",rating:8.2,foreign:true},
{name:"Daryl Mitchell",role:"ALL",rating:8.5,foreign:true},

{name:"Sikandar Raza",role:"ALL",rating:8.6,foreign:true},
{name:"Shakib Al Hasan",role:"ALL",rating:9.4,foreign:true},
{name:"Ben Stokes",role:"ALL",rating:9.3,foreign:true},
{name:"Glenn Maxwell",role:"ALL",rating:9.1,foreign:true},
{name:"Mohammad Nabi",role:"ALL",rating:8.4,foreign:true},
{name:"Kyle Mayers",role:"ALL",rating:8.3,foreign:true},
{name:"Roston Chase",role:"ALL",rating:8.0,foreign:true},
{name:"Daniel Sams",role:"ALL",rating:8.1,foreign:true},
{name:"Sean Abbott",role:"ALL",rating:8.2,foreign:true},
{name:"Chris Woakes",role:"ALL",rating:8.8,foreign:true},

/* ======================= PACE BOWLERS (20) ======================= */
{name:"Jasprit Bumrah",role:"PACE",rating:9.8,foreign:false},
{name:"Mohammed Shami",role:"PACE",rating:9.4,foreign:false},
{name:"Mohammed Siraj",role:"PACE",rating:9.0,foreign:false},
{name:"Arshdeep Singh",role:"PACE",rating:8.8,foreign:false},
{name:"Bhuvneshwar Kumar",role:"PACE",rating:8.9,foreign:false},
{name:"Deepak Chahar",role:"PACE",rating:8.5,foreign:false},
{name:"Prasidh Krishna",role:"PACE",rating:8.3,foreign:false},
{name:"Umran Malik",role:"PACE",rating:8.0,foreign:false},
{name:"Ishant Sharma",role:"PACE",rating:8.1,foreign:false},
{name:"Mukesh Kumar",role:"PACE",rating:7.9,foreign:false},

{name:"Mitchell Starc",role:"PACE",rating:9.5,foreign:true},
{name:"Kagiso Rabada",role:"PACE",rating:9.3,foreign:true},
{name:"Trent Boult",role:"PACE",rating:9.2,foreign:true},
{name:"Pat Cummins",role:"PACE",rating:9.1,foreign:true},
{name:"Anrich Nortje",role:"PACE",rating:8.8,foreign:true},
{name:"Lockie Ferguson",role:"PACE",rating:8.7,foreign:true},
{name:"Josh Hazlewood",role:"PACE",rating:9.0,foreign:true},
{name:"Alzarri Joseph",role:"PACE",rating:8.6,foreign:true},
{name:"Mark Wood",role:"PACE",rating:8.9,foreign:true},
{name:"Tim Southee",role:"PACE",rating:8.4,foreign:true},

/* ======================= SPIN BOWLERS (20) ======================= */
{name:"Yuzvendra Chahal",role:"SPIN",rating:9.2,foreign:false},
{name:"Kuldeep Yadav",role:"SPIN",rating:9.0,foreign:false},
{name:"Ravichandran Ashwin",role:"SPIN",rating:9.1,foreign:false},
{name:"Rahul Chahar",role:"SPIN",rating:8.4,foreign:false},
{name:"Washington Sundar",role:"SPIN",rating:8.2,foreign:false},
{name:"Varun Chakravarthy",role:"SPIN",rating:8.8,foreign:false},
{name:"Mayank Markande",role:"SPIN",rating:7.9,foreign:false},
{name:"R Sai Kishore",role:"SPIN",rating:8.3,foreign:false},
{name:"Shahbaz Ahmed",role:"SPIN",rating:8.1,foreign:false},
{name:"Amit Mishra",role:"SPIN",rating:8.0,foreign:false},

{name:"Rashid Khan",role:"SPIN",rating:9.7,foreign:true},
{name:"Adam Zampa",role:"SPIN",rating:8.9,foreign:true},
{name:"Mujeeb Ur Rahman",role:"SPIN",rating:8.8,foreign:true},
{name:"Tabraiz Shamsi",role:"SPIN",rating:8.7,foreign:true},
{name:"Maheesh Theekshana",role:"SPIN",rating:8.6,foreign:true},
{name:"Akeal Hosein",role:"SPIN",rating:8.5,foreign:true},
{name:"Noor Ahmad",role:"SPIN",rating:8.4,foreign:true},
{name:"Ish Sodhi",role:"SPIN",rating:8.3,foreign:true},
{name:"Wanindu Hasaranga (Spin)",role:"SPIN",rating:8.9,foreign:true},
{name:"Sunil Narine (Spin)",role:"SPIN",rating:8.8,foreign:true}

];
