module.exports = [

/* ============================================================ */
/* WICKET KEEPERS                         */
/* ============================================================ */

/* --- Indian Wicket Keepers --- */
{name:"KL Rahul", role:"WK", rating:9.3, foreign:false},
{name:"Sanju Samson", role:"WK", rating:9.1, foreign:false},
{name:"MS Dhoni", role:"WK", rating:8.9, foreign:false},
{name:"Rishabh Pant", role:"WK", rating:8.9, foreign:false},
{name:"Ishan Kishan", role:"WK", rating:8.9, foreign:false},
{name:"Prabhsimran Singh", role:"WK", rating:8.7, foreign:false},
{name:"Wriddhiman Saha", role:"WK", rating:8.2, foreign:false},
{name:"Jitesh Sharma", role:"WK", rating:8.2, foreign:false},
{name:"Abhishek Porel", role:"WK", rating:8.1, foreign:false},
{name:"Dhruv Jurel", role:"WK", rating:8.0, foreign:false},
{name:"Urvil Patel", role:"WK", rating:7.7, foreign:false},
{name:"KS Bharat", role:"WK", rating:7.6, foreign:false},
{name:"Anuj Rawat", role:"WK", rating:7.6, foreign:false},
{name:"Narayan Jagadeesan", role:"WK", rating:7.5, foreign:false},
{name:"Kumar Kushagra", role:"WK", rating:7.5, foreign:false},
{name:"Ricky Bhui", role:"WK", rating:7.4, foreign:false},
{name:"Vishnu Vinod", role:"WK", rating:7.3, foreign:false},
{name:"Robin Minz", role:"WK", rating:7.1, foreign:false},
{name:"Upendra Yadav", role:"WK", rating:7.0, foreign:false},
{name:"Aryan Juyal", role:"WK", rating:6.9, foreign:false},
{name:"Harvik Desai", role:"WK", rating:6.9, foreign:false},
{name:"BR Sharath", role:"WK", rating:6.8, foreign:false},
{name:"Luvnith Sisodia", role:"WK", rating:6.7, foreign:false},
{name:"Avanish Rao Aravelly", role:"WK", rating:6.5, foreign:false},

/* --- Overseas Wicket Keepers --- */
{name:"Jos Buttler", role:"WK", rating:9.9, foreign:true},
{name:"Nicholas Pooran", role:"WK", rating:9.7, foreign:true},
{name:"Heinrich Klaasen", role:"WK", rating:9.5, foreign:true},
{name:"Phil Salt", role:"WK", rating:9.5, foreign:true},
{name:"Quinton de Kock", role:"WK", rating:9.1, foreign:true},
{name:"Josh Inglis", role:"WK", rating:9.0, foreign:true},
{name:"Ryan Rickelton", role:"WK", rating:8.9, foreign:true},
{name:"Devon Conway", role:"WK", rating:8.7, foreign:true}, 
{name:"Jonny Bairstow", role:"WK", rating:8.6, foreign:true},
{name:"Tristan Stubbs", role:"WK", rating:8.6, foreign:true},
{name:"Rahmanullah Gurbaz", role:"WK", rating:8.5, foreign:true},
{name:"Kusal Mendis", role:"WK", rating:8.4, foreign:true},
{name:"Matthew Wade", role:"WK", rating:7.7, foreign:true},
{name:"Alex Carey", role:"WK", rating:7.6, foreign:true},
{name:"Tom Kohler-Cadmore", role:"WK", rating:7.6, foreign:true},
{name:"Shai Hope", role:"WK", rating:7.2, foreign:true},
{name:"Donovan Ferreira", role:"WK", rating:7.1, foreign:true},
{name:"Finn Allen", role:"WK", rating:7.0, foreign:true},
{name:"Ben McDermott", role:"WK", rating:6.9, foreign:true},


/* ============================================================ */
/* BATSMEN                             */
/* ============================================================ */

/* --- Indian Batsmen --- */
{name:"Virat Kohli", role:"BAT", rating:10.0, foreign:false},
{name:"Suryakumar Yadav", role:"BAT", rating:9.7, foreign:false},
{name:"Shreyas Iyer", role:"BAT", rating:9.6, foreign:false},
{name:"Rohit Sharma", role:"BAT", rating:9.5, foreign:false},
{name:"Shubman Gill", role:"BAT", rating:9.2, foreign:false},
{name:"Yashasvi Jaiswal", role:"BAT", rating:9.2, foreign:false},
{name:"Tilak Varma", role:"BAT", rating:9.1, foreign:false},
{name:"Sai Sudharsan", role:"BAT", rating:9.0, foreign:false},
{name:"Rajat Patidar", role:"BAT", rating:8.9, foreign:false},
{name:"Shashank Singh", role:"BAT", rating:8.9, foreign:false},
{name:"Ashutosh Sharma", role:"BAT", rating:8.8, foreign:false},
{name:"Ruturaj Gaikwad", role:"BAT", rating:8.7, foreign:false},
{name:"Ajinkya Rahane", role:"BAT", rating:8.6, foreign:false},
{name:"Angkrish Raghuvanshi", role:"BAT", rating:8.6, foreign:false},
{name:"Rinku Singh", role:"BAT", rating:8.4, foreign:false},
{name:"Nehal Wadhera", role:"BAT", rating:8.4, foreign:false},
{name:"Ayush Mhatre", role:"BAT", rating:8.4, foreign:false},
{name:"Sarfaraz Khan", role:"BAT", rating:8.3, foreign:false},
{name:"Vaibhav Suryabanshi", role:"BAT", rating:8.3, foreign:false},
{name:"Priyansh Arya", role:"BAT", rating:8.3, foreign:false},
{name:"Devdutt Padikkal", role:"BAT", rating:8.2, foreign:false},
{name:"Ayush Badoni", role:"BAT", rating:8.1, foreign:false},
{name:"Abhinav Manohar", role:"BAT", rating:8.0, foreign:false},
{name:"Mayank Agarwal", role:"BAT", rating:8.0, foreign:false},
{name:"Abdul Samad", role:"BAT", rating:8.0, foreign:false},
{name:"Naman Dhir", role:"BAT", rating:8.0, foreign:false},
{name:"Rahul Tripathi", role:"BAT", rating:7.9, foreign:false},
{name:"Mahipal Lomror", role:"BAT", rating:7.9, foreign:false},
{name:"Nitish Rana", role:"BAT", rating:7.8, foreign:false},
{name:"Prithvi Shaw", role:"BAT", rating:7.8, foreign:false},
{name:"Manish Pandey", role:"BAT", rating:7.7, foreign:false},
{name:"Sameer Rizvi", role:"BAT", rating:7.7, foreign:false},
{name:"Shaik Rasheed", role:"BAT", rating:7.7, foreign:false},
{name:"Shah Rukh Khan", role:"BAT", rating:7.6, foreign:false},
{name:"Karun Nair", role:"BAT", rating:7.6, foreign:false},
{name:"Atharva Taide", role:"BAT", rating:7.5, foreign:false},
{name:"Suyash Prabhudessai", role:"BAT", rating:7.4, foreign:false},
{name:"Vijay Shankar", role:"BAT", rating:7.3, foreign:false},
{name:"Shubham Dubey", role:"BAT", rating:7.2, foreign:false},
{name:"Himmat Singh", role:"BAT", rating:7.0, foreign:false},
{name:"Sachin Baby", role:"BAT", rating:6.9, foreign:false},
{name:"Swastik Chhikara", role:"BAT", rating:6.8, foreign:false},
{name:"Musheer Khan", role:"BAT", rating:6.7, foreign:false},

/* --- Overseas Batsmen --- */
{name:"Travis Head", role:"BAT", rating:9.8, foreign:true},
{name:"Aiden Markram", role:"BAT", rating:9.0, foreign:true},
{name:"Tim David", role:"BAT", rating:8.8, foreign:true},
{name:"Dewald Brevis", role:"BAT", rating:8.7, foreign:true},
{name:"Faf du Plessis", role:"BAT", rating:8.6, foreign:true},
{name:"Sherfane Rutherford", role:"BAT", rating:8.6, foreign:true},
{name:"Pathum Nissanka", role:"BAT", rating:8.4, foreign:true},
{name:"Kusal Perera", role:"BAT", rating:8.4, foreign:true},
{name:"David Miller", role:"BAT", rating:8.3, foreign:true},
{name:"Kane Williamson", role:"BAT", rating:8.3, foreign:true},
{name:"Glenn Phillips", role:"BAT", rating:8.3, foreign:true},
{name:"Shimron Hetmyer", role:"BAT", rating:8.2, foreign:true},
{name:"Jake Fraser-McGurk", role:"BAT", rating:8.0, foreign:true},
{name:"Steve Smith", role:"BAT", rating:8.0, foreign:true},
{name:"Rovman Powell", role:"BAT", rating:7.9, foreign:true},
{name:"Jason Roy", role:"BAT", rating:7.8, foreign:true},
{name:"Harry Brook", role:"BAT", rating:7.7, foreign:true},
{name:"Charith Asalanka", role:"BAT", rating:7.6, foreign:true},
{name:"Matthew Short", role:"BAT", rating:7.6, foreign:true},
{name:"Alex Hales", role:"BAT", rating:7.5, foreign:true},
{name:"Najibullah Zadran", role:"BAT", rating:7.5, foreign:true},
{name:"Saim Ayub", role:"BAT", rating:7.4, foreign:true},


/* ============================================================ */
/* ALL ROUNDERS                          */
/* ============================================================ */

/* --- Indian All Rounders --- */
{name:"Hardik Pandya", role:"ALL", rating:9.9, foreign:false},
{name:"Abhishek Sharma", role:"ALL", rating:9.5, foreign:false},
{name:"Ravindra Jadeja", role:"ALL", rating:9.4, foreign:false},
{name:"Axar Patel", role:"ALL", rating:9.2, foreign:false},
{name:"Riyan Parag", role:"ALL", rating:9.1, foreign:false},
{name:"Krunal Pandya", role:"ALL", rating:8.9, foreign:false},
{name:"Nitish Kumar Reddy", role:"ALL", rating:8.5, foreign:false},
{name:"Washington Sundar", role:"ALL", rating:8.4, foreign:false},
{name:"Shivam Dube", role:"ALL", rating:8.3, foreign:false},
{name:"Venkatesh Iyer", role:"ALL", rating:8.3, foreign:false},
{name:"Shardul Thakur", role:"ALL", rating:8.1, foreign:false},
{name:"Ramandeep Singh", role:"ALL", rating:7.8, foreign:false},
{name:"Shahbaz Ahmed", role:"ALL", rating:7.7, foreign:false},
{name:"Y Singh Charak", role:"ALL", rating:7.5, foreign:false},
{name:"Deepak Hooda", role:"ALL", rating:7.4, foreign:false},
{name:"Swapnil Singh", role:"ALL", rating:7.3, foreign:false},
{name:"Ripal Patel", role:"ALL", rating:6.9, foreign:false},
{name:"Shams Mulani", role:"ALL", rating:6.8, foreign:false},

/* --- Overseas All Rounders --- */
{name:"Sunil Narine", role:"ALL", rating:9.6, foreign:true},
{name:"Mitchell Marsh", role:"ALL", rating:9.3, foreign:true},
{name:"Sam Curran", role:"ALL", rating:9.0, foreign:true},
{name:"Andre Russell", role:"ALL", rating:8.9, foreign:true},
{name:"Marcus Stoinis", role:"ALL", rating:8.9, foreign:true},
{name:"Will Jacks", role:"ALL", rating:8.9, foreign:true},
{name:"Cameron Green", role:"ALL", rating:8.8, foreign:true},
{name:"Marco Jansen", role:"ALL", rating:8.8, foreign:true},
{name:"Romario Shepherd", role:"ALL", rating:8.7, foreign:true},
{name:"Mitchell Santner", role:"ALL", rating:8.6, foreign:true},
{name:"Rachin Ravindra", role:"ALL", rating:8.5, foreign:true},
{name:"Ben Stokes", role:"ALL", rating:8.4, foreign:true},
{name:"Azmatullah Omarzai", role:"ALL", rating:8.4, foreign:true},
{name:"Mohammad Nabi", role:"ALL", rating:8.4, foreign:true},
{name:"Liam Livingstone", role:"ALL", rating:8.2, foreign:true},
{name:"Glenn Maxwell", role:"ALL", rating:8.1, foreign:true},
{name:"Daryl Mitchell", role:"ALL", rating:8.0, foreign:true},
{name:"Jason Holder", role:"ALL", rating:7.9, foreign:true},
{name:"Chris Woakes", role:"ALL", rating:7.8, foreign:true},
{name:"Daniel Sams", role:"ALL", rating:7.4, foreign:true},
{name:"Kyle Mayers", role:"ALL", rating:7.3, foreign:true},


/* ============================================================ */
/* PACE BOWLERS                          */
/* ============================================================ */

/* --- Indian Pace Bowlers --- */
{name:"Jasprit Bumrah", role:"PACE", rating:10.0, foreign:false},
{name:"Arshdeep Singh", role:"PACE", rating:9.6, foreign:false},
{name:"Harshal Patel", role:"PACE", rating:9.5, foreign:false},
{name:"Mohammed Siraj", role:"PACE", rating:9.0, foreign:false},
{name:"Bhuvaneshwar Kumar", role:"PACE", rating:9.0, foreign:false},
{name:"Prasidh Krishna", role:"PACE", rating:9.0, foreign:false},
{name:"Mohammed Shami", role:"PACE", rating:8.9, foreign:false},
{name:"T Natarajan", role:"PACE", rating:8.8, foreign:false},
{name:"Harshit Rana", role:"PACE", rating:8.7, foreign:false},
{name:"Deepak Chahar", role:"PACE", rating:8.6, foreign:false},
{name:"Tushar Deshpande", role:"PACE", rating:8.6, foreign:false},
{name:"Yash Dayal", role:"PACE", rating:8.5, foreign:false},
{name:"Khaleel Ahmed", role:"PACE", rating:8.3, foreign:false},
{name:"Sandeep Sharma", role:"PACE", rating:8.3, foreign:false},
{name:"Vaibhav Arora", role:"PACE", rating:8.3, foreign:false},
{name:"Mukesh Kumar", role:"PACE", rating:8.2, foreign:false},
{name:"Mohsin Khan", role:"PACE", rating:8.2, foreign:false},
{name:"Ishant Sharma", role:"PACE", rating:8.1, foreign:false},
{name:"Akash Madhwal", role:"PACE", rating:8.1, foreign:false},
{name:"Avesh Khan", role:"PACE", rating:8.1, foreign:false},
{name:"Jaydev Unadkat", role:"PACE", rating:8.1, foreign:false},
{name:"Akash Deep", role:"PACE", rating:8.1, foreign:false},
{name:"Vijaykumar Vyshak", role:"PACE", rating:8.0, foreign:false},
{name:"Umesh Yadav", role:"PACE", rating:7.9, foreign:false},
{name:"Umran Malik", role:"PACE", rating:7.9, foreign:false},
{name:"Shivam Mavi", role:"PACE", rating:7.9, foreign:false},
{name:"Mayank Yadav", role:"PACE", rating:7.8, foreign:false},
{name:"Yash Thakur", role:"PACE", rating:7.8, foreign:false},
{name:"Rasikh Salam", role:"PACE", rating:7.8, foreign:false},
{name:"Simarjeet Singh", role:"PACE", rating:7.8, foreign:false},
{name:"Anshul Kamboj", role:"PACE", rating:7.8, foreign:false},
{name:"Kuldeep Sen", role:"PACE", rating:7.8, foreign:false},
{name:"Kartik Tyagi", role:"PACE", rating:7.7, foreign:false},
{name:"Mukesh Choudhary", role:"PACE", rating:7.7, foreign:false},
{name:"Sandeep Warrier", role:"PACE", rating:7.5, foreign:false},
{name:"Navdeep Saini", role:"PACE", rating:7.3, foreign:false},
{name:"Chetan Sakariya", role:"PACE", rating:7.0, foreign:false},
{name:"Arjun Tendulkar", role:"PACE", rating:6.0, foreign:false},

/* --- Overseas Pace Bowlers --- */
{name:"Josh Hazlewood", role:"PACE", rating:9.8, foreign:true},
{name:"Trent Boult", role:"PACE", rating:9.6, foreign:true},
{name:"Mitchell Starc", role:"PACE", rating:9.4, foreign:true},
{name:"Pat Cummins", role:"PACE", rating:9.4, foreign:true},
{name:"Kagiso Rabada", role:"PACE", rating:9.2, foreign:true},
{name:"Matheesha Pathirana", role:"PACE", rating:9.0, foreign:true},
{name:"Mustafizur Rahman", role:"PACE", rating:8.8, foreign:true},
{name:"Anrich Nortje", role:"PACE", rating:8.7, foreign:true},
{name:"Lockie Ferguson", role:"PACE", rating:8.7, foreign:true},
{name:"Naveen-ul-Haq", role:"PACE", rating:8.7, foreign:true},
{name:"Gerald Coetzee", role:"PACE", rating:8.6, foreign:true},
{name:"Nandre Burger", role:"PACE", rating:8.4, foreign:true},
{name:"Jason Behrendorff", role:"PACE", rating:8.3, foreign:true},
{name:"Nathan Ellis", role:"PACE", rating:8.3, foreign:true},
{name:"Matt Henry", role:"PACE", rating:8.2, foreign:true},
{name:"Lungi Ngidi", role:"PACE", rating:8.1, foreign:true},
{name:"Nuwan Thushara", role:"PACE", rating:8.0, foreign:true},
{name:"Josh Little", role:"PACE", rating:8.0, foreign:true},
{name:"Gus Atkinson", role:"PACE", rating:8.0, foreign:true},
{name:"Mark Wood", role:"PACE", rating:7.9, foreign:true},
{name:"Dilshan Madushanka", role:"PACE", rating:7.9, foreign:true},
{name:"Jhye Richardson", role:"PACE", rating:7.9, foreign:true},
{name:"Reece Topley", role:"PACE", rating:7.8, foreign:true},
{name:"Fazalhaq Farooqi", role:"PACE", rating:7.7, foreign:true},
{name:"Alzarri Joseph", role:"PACE", rating:7.6, foreign:true},
{name:"Spencer Johnson", role:"PACE", rating:7.6, foreign:true},
{name:"Dushmantha Chameera", role:"PACE", rating:7.5, foreign:true},
{name:"Wayne Parnell", role:"PACE", rating:7.4, foreign:true},
{name:"Luke Wood", role:"PACE", rating:7.3, foreign:true},
{name:"Obed McCoy", role:"PACE", rating:7.2, foreign:true},
{name:"Tom Curran", role:"PACE", rating:7.2, foreign:true},
{name:"Richard Gleeson", role:"PACE", rating:7.0, foreign:true},
{name:"B Muzarabani", role:"PACE", rating:6.9, foreign:true},
{name:"Shamar Joseph", role:"PACE", rating:6.9, foreign:true},
{name:"Kwena Maphaka", role:"PACE", rating:6.8, foreign:true},
{name:"Lizaad Williams", role:"PACE", rating:6.8, foreign:true},


/* ============================================================ */
/* SPIN BOWLERS                          */
/* ============================================================ */

/* --- Indian Spin Bowlers --- */
{name:"Varun Chakravarthy", role:"SPIN", rating:9.6, foreign:false},
{name:"Kuldeep Yadav", role:"SPIN", rating:9.5, foreign:false},
{name:"Yuzvendra Chahal", role:"SPIN", rating:9.4, foreign:false},
{name:"Ravi Bishnoi", role:"SPIN", rating:8.8, foreign:false},
{name:"R Sai Kishore", role:"SPIN", rating:8.6, foreign:false},
{name:"Suyash Sharma", role:"SPIN", rating:8.4, foreign:false},
{name:"Digvesh Rathi", role:"SPIN", rating:8.3, foreign:false},
{name:"Rahul Chahar", role:"SPIN", rating:8.2, foreign:false},
{name:"Mayank Markande", role:"SPIN", rating:7.9, foreign:false},
{name:"Vignesh Puthur", role:"SPIN", rating:7.9, foreign:false},
{name:"Karn Sharma", role:"SPIN", rating:7.7, foreign:false},
{name:"Piyush Chawla", role:"SPIN", rating:7.4, foreign:false},
{name:"Shreyas Gopal", role:"SPIN", rating:7.0, foreign:false},
{name:"Murugan Ashwin", role:"SPIN", rating:6.9, foreign:false},
{name:"Tanush Kotian", role:"SPIN", rating:6.8, foreign:false},
{name:"Manav Suthar", role:"SPIN", rating:6.7, foreign:false},

/* --- Overseas Spin Bowlers --- */
{name:"Rashid Khan", role:"SPIN", rating:9.7, foreign:true},
{name:"Noor Ahmad", role:"SPIN", rating:9.2, foreign:true},
{name:"Adam Zampa", role:"SPIN", rating:8.9, foreign:true},
{name:"Maheesh Theekshana", role:"SPIN", rating:8.6, foreign:true},
{name:"Wanindu Hasaranga", role:"SPIN", rating:8.6, foreign:true},
{name:"Mujeeb Ur Rahman", role:"SPIN", rating:8.5, foreign:true},
{name:"Keshav Maharaj", role:"SPIN", rating:7.8, foreign:true},
{name:"Adil Rashid", role:"SPIN", rating:7.8, foreign:true},
{name:"Tabraiz Shamsi", role:"SPIN", rating:7.7, foreign:true},
{name:"Allah Ghazanfar", role:"SPIN", rating:7.6, foreign:true},
{name:"Akeal Hosein", role:"SPIN", rating:7.5, foreign:true},
{name:"Ish Sodhi", role:"SPIN", rating:7.4, foreign:true},
{name:"Vijayakanth Viyaskanth", role:"SPIN", rating:7.1, foreign:true}

];
