module.exports = [

/* ============================================================ */
/* WICKET KEEPERS                         */
/* ============================================================ */

/* --- Indian Wicket Keepers --- */
{name:"KL Rahul", role:"WK", rating:9.3, foreign:false, tag:"WK1"},
{name:"Sanju Samson", role:"WK", rating:9.1, foreign:false, tag:"WK1"},
{name:"MS Dhoni", role:"WK", rating:8.9, foreign:false, tag:"WK1"},
{name:"Rishabh Pant", role:"WK", rating:8.9, foreign:false, tag:"WK1"},
{name:"Ishan Kishan", role:"WK", rating:8.9, foreign:false, tag:"WK1"},
{name:"Prabhsimran Singh", role:"WK", rating:8.7, foreign:false, tag:"WK2"},
{name:"Wriddhiman Saha", role:"WK", rating:8.2, foreign:false, tag:"WK1"},
{name:"Jitesh Sharma", role:"WK", rating:8.2, foreign:false, tag:"WK2"},
{name:"Abhishek Porel", role:"WK", rating:8.1, foreign:false, tag:"WK2"},
{name:"Dhruv Jurel", role:"WK", rating:8.0, foreign:false, tag:"WK2"},
{name:"Urvil Patel", role:"WK", rating:7.7, foreign:false, tag:"WK2"},
{name:"KS Bharat", role:"WK", rating:7.6, foreign:false, tag:"WK1"},
{name:"Anuj Rawat", role:"WK", rating:7.6, foreign:false, tag:"WK2"},
{name:"Narayan Jagadeesan", role:"WK", rating:7.5, foreign:false, tag:"WK2"},
{name:"Kumar Kushagra", role:"WK", rating:7.5, foreign:false, tag:"WK2"},
{name:"Ricky Bhui", role:"WK", rating:7.4, foreign:false, tag:"WK2"},
{name:"Vishnu Vinod", role:"WK", rating:7.3, foreign:false, tag:"WK2"},
{name:"Robin Minz", role:"WK", rating:7.1, foreign:false, tag:"WK2"},
{name:"Upendra Yadav", role:"WK", rating:7.0, foreign:false, tag:"WK2"},
{name:"Aryan Juyal", role:"WK", rating:6.9, foreign:false, tag:"WK2"},
{name:"Harvik Desai", role:"WK", rating:6.9, foreign:false, tag:"WK2"},
{name:"BR Sharath", role:"WK", rating:6.8, foreign:false, tag:"WK2"},
{name:"Luvnith Sisodia", role:"WK", rating:6.7, foreign:false, tag:"WK2"},
{name:"Avanish Rao Aravelly", role:"WK", rating:6.5, foreign:false, tag:"WK2"},

/* --- Overseas Wicket Keepers --- */
{name:"Jos Buttler", role:"WK", rating:9.9, foreign:true, tag:"M"},
{name:"Nicholas Pooran", role:"WK", rating:9.7, foreign:true, tag:"WK1"},
{name:"Heinrich Klaasen", role:"WK", rating:9.5, foreign:true, tag:"WK1"},
{name:"Phil Salt", role:"WK", rating:9.5, foreign:true, tag:"WK1"},
{name:"Quinton de Kock", role:"WK", rating:9.1, foreign:true, tag:"WK1"},
{name:"Josh Inglis", role:"WK", rating:9.0, foreign:true, tag:"WK1"},
{name:"Ryan Rickelton", role:"WK", rating:8.9, foreign:true, tag:"WK1"},
{name:"Devon Conway", role:"WK", rating:8.7, foreign:true, tag:"WK1"},
{name:"Jonny Bairstow", role:"WK", rating:8.6, foreign:true, tag:"WK1"},
{name:"Tristan Stubbs", role:"WK", rating:8.6, foreign:true, tag:"WK1"},
{name:"Rahmanullah Gurbaz", role:"WK", rating:8.5, foreign:true, tag:"WK1"},
{name:"Kusal Mendis", role:"WK", rating:8.4, foreign:true, tag:"WK1"},
{name:"Matthew Wade", role:"WK", rating:7.7, foreign:true, tag:"WK1"},
{name:"Alex Carey", role:"WK", rating:7.6, foreign:true, tag:"WK1"},
{name:"Tom Kohler-Cadmore", role:"WK", rating:7.6, foreign:true, tag:"WK1"},
{name:"Shai Hope", role:"WK", rating:7.2, foreign:true, tag:"WK1"},
{name:"Donovan Ferreira", role:"WK", rating:7.1, foreign:true, tag:"WK2"},
{name:"Finn Allen", role:"WK", rating:7.0, foreign:true, tag:"WK1"},
{name:"Ben McDermott", role:"WK", rating:6.9, foreign:true, tag:"WK1"},

/* ============================================================ */
/* BATSMEN                             */
/* ============================================================ */

/* --- Indian Batsmen --- */
{name:"Virat Kohli", role:"BAT", rating:10.0, foreign:false, tag:"M"},
{name:"Suryakumar Yadav", role:"BAT", rating:9.7, foreign:false, tag:"BAT1"},
{name:"Shreyas Iyer", role:"BAT", rating:9.6, foreign:false, tag:"BAT1"},
{name:"Rohit Sharma", role:"BAT", rating:9.5, foreign:false, tag:"BAT1"},
{name:"Shubman Gill", role:"BAT", rating:9.2, foreign:false, tag:"BAT1"},
{name:"Yashasvi Jaiswal", role:"BAT", rating:9.2, foreign:false, tag:"BAT1"},
{name:"Tilak Varma", role:"BAT", rating:9.1, foreign:false, tag:"BAT1"},
{name:"Sai Sudharsan", role:"BAT", rating:9.0, foreign:false, tag:"BAT2"},
{name:"Rajat Patidar", role:"BAT", rating:8.9, foreign:false, tag:"BAT1"},
{name:"Shashank Singh", role:"BAT", rating:8.9, foreign:false, tag:"BAT2"},
{name:"Ashutosh Sharma", role:"BAT", rating:8.8, foreign:false, tag:"BAT2"},
{name:"Ruturaj Gaikwad", role:"BAT", rating:8.7, foreign:false, tag:"BAT1"},
{name:"Ajinkya Rahane", role:"BAT", rating:8.6, foreign:false, tag:"BAT1"},
{name:"Angkrish Raghuvanshi", role:"BAT", rating:8.6, foreign:false, tag:"BAT2"},
{name:"Rinku Singh", role:"BAT", rating:8.4, foreign:false, tag:"BAT2"},
{name:"Nehal Wadhera", role:"BAT", rating:8.4, foreign:false, tag:"BAT2"},
{name:"Ayush Mhatre", role:"BAT", rating:8.4, foreign:false, tag:"BAT2"},
{name:"Sarfaraz Khan", role:"BAT", rating:8.3, foreign:false, tag:"BAT1"},
{name:"Vaibhav Suryabanshi", role:"BAT", rating:8.3, foreign:false, tag:"BAT2"},
{name:"Priyansh Arya", role:"BAT", rating:8.3, foreign:false, tag:"BAT2"},
{name:"Devdutt Padikkal", role:"BAT", rating:8.2, foreign:false, tag:"BAT1"},
{name:"Ayush Badoni", role:"BAT", rating:8.1, foreign:false, tag:"BAT2"},
{name:"Abhinav Manohar", role:"BAT", rating:8.0, foreign:false, tag:"BAT2"},
{name:"Mayank Agarwal", role:"BAT", rating:8.0, foreign:false, tag:"BAT1"},
{name:"Abdul Samad", role:"BAT", rating:8.0, foreign:false, tag:"BAT2"},
{name:"Naman Dhir", role:"BAT", rating:8.0, foreign:false, tag:"BAT2"},
{name:"Rahul Tripathi", role:"BAT", rating:7.9, foreign:false, tag:"BAT1"},
{name:"Mahipal Lomror", role:"BAT", rating:7.9, foreign:false, tag:"BAT2"},
{name:"Nitish Rana", role:"BAT", rating:7.8, foreign:false, tag:"BAT1"},
{name:"Prithvi Shaw", role:"BAT", rating:7.8, foreign:false, tag:"BAT1"},
{name:"Manish Pandey", role:"BAT", rating:7.7, foreign:false, tag:"BAT1"},
{name:"Sameer Rizvi", role:"BAT", rating:7.7, foreign:false, tag:"BAT2"},
{name:"Shaik Rasheed", role:"BAT", rating:7.7, foreign:false, tag:"BAT2"},
{name:"Shah Rukh Khan", role:"BAT", rating:7.6, foreign:false, tag:"BAT2"},
{name:"Karun Nair", role:"BAT", rating:7.6, foreign:false, tag:"BAT1"},
{name:"Atharva Taide", role:"BAT", rating:7.5, foreign:false, tag:"BAT2"},
{name:"Suyash Prabhudessai", role:"BAT", rating:7.4, foreign:false, tag:"BAT2"},
{name:"Vijay Shankar", role:"BAT", rating:7.3, foreign:false, tag:"BAT1"},
{name:"Shubham Dubey", role:"BAT", rating:7.2, foreign:false, tag:"BAT2"},
{name:"Himmat Singh", role:"BAT", rating:7.0, foreign:false, tag:"BAT2"},
{name:"Sachin Baby", role:"BAT", rating:6.9, foreign:false, tag:"BAT1"},
{name:"Swastik Chhikara", role:"BAT", rating:6.8, foreign:false, tag:"BAT2"},
{name:"Musheer Khan", role:"BAT", rating:6.7, foreign:false, tag:"BAT2"},

/* ============================================================ */
/* ALL ROUNDERS                          */
/* ============================================================ */

/* --- Indian All Rounders --- */
{name:"Hardik Pandya", role:"ALL", rating:9.9, foreign:false, tag:"M"},
{name:"Abhishek Sharma", role:"ALL", rating:9.5, foreign:false, tag:"ALL1"},
{name:"Ravindra Jadeja", role:"ALL", rating:9.4, foreign:false, tag:"ALL1"},
{name:"Axar Patel", role:"ALL", rating:9.2, foreign:false, tag:"ALL1"},
{name:"Riyan Parag", role:"ALL", rating:9.1, foreign:false, tag:"ALL2"},
{name:"Krunal Pandya", role:"ALL", rating:8.9, foreign:false, tag:"ALL1"},
{name:"Nitish Kumar Reddy", role:"ALL", rating:8.5, foreign:false, tag:"ALL2"},
{name:"Washington Sundar", role:"ALL", rating:8.4, foreign:false, tag:"ALL1"},
{name:"Shivam Dube", role:"ALL", rating:8.3, foreign:false, tag:"ALL1"},
{name:"Venkatesh Iyer", role:"ALL", rating:8.3, foreign:false, tag:"ALL1"},
{name:"Shardul Thakur", role:"ALL", rating:8.1, foreign:false, tag:"ALL1"},
{name:"Ramandeep Singh", role:"ALL", rating:7.8, foreign:false, tag:"ALL2"},
{name:"Shahbaz Ahmed", role:"ALL", rating:7.7, foreign:false, tag:"ALL1"},
{name:"Y Singh Charak", role:"ALL", rating:7.5, foreign:false, tag:"ALL2"},
{name:"Deepak Hooda", role:"ALL", rating:7.4, foreign:false, tag:"ALL1"},
{name:"Swapnil Singh", role:"ALL", rating:7.3, foreign:false, tag:"ALL2"},
{name:"Ripal Patel", role:"ALL", rating:6.9, foreign:false, tag:"ALL2"},
{name:"Shams Mulani", role:"ALL", rating:6.8, foreign:false, tag:"ALL2"},

/* ============================================================ */
/* PACE BOWLERS                          */
/* ============================================================ */

{name:"Jasprit Bumrah", role:"PACE", rating:10.0, foreign:false, tag:"M"},
{name:"Arshdeep Singh", role:"PACE", rating:9.6, foreign:false, tag:"BOWL1"},
{name:"Harshal Patel", role:"PACE", rating:9.5, foreign:false, tag:"BOWL1"},
{name:"Mohammed Siraj", role:"PACE", rating:9.0, foreign:false, tag:"BOWL1"},
{name:"Bhuvaneshwar Kumar", role:"PACE", rating:9.0, foreign:false, tag:"BOWL1"},
{name:"Prasidh Krishna", role:"PACE", rating:9.0, foreign:false, tag:"BOWL1"},
{name:"Mohammed Shami", role:"PACE", rating:8.9, foreign:false, tag:"BOWL1"},
{name:"T Natarajan", role:"PACE", rating:8.8, foreign:false, tag:"BOWL1"},
{name:"Harshit Rana", role:"PACE", rating:8.7, foreign:false, tag:"BOWL2"},
{name:"Deepak Chahar", role:"PACE", rating:8.6, foreign:false, tag:"BOWL1"},
{name:"Tushar Deshpande", role:"PACE", rating:8.6, foreign:false, tag:"BOWL2"},
{name:"Yash Dayal", role:"PACE", rating:8.5, foreign:false, tag:"BOWL2"},
{name:"Khaleel Ahmed", role:"PACE", rating:8.3, foreign:false, tag:"BOWL1"},
{name:"Sandeep Sharma", role:"PACE", rating:8.3, foreign:false, tag:"BOWL1"},
{name:"Vaibhav Arora", role:"PACE", rating:8.3, foreign:false, tag:"BOWL2"},
{name:"Mukesh Kumar", role:"PACE", rating:8.2, foreign:false, tag:"BOWL2"},
{name:"Mohsin Khan", role:"PACE", rating:8.2, foreign:false, tag:"BOWL2"},
{name:"Ishant Sharma", role:"PACE", rating:8.1, foreign:false, tag:"BOWL1"},
{name:"Akash Madhwal", role:"PACE", rating:8.1, foreign:false, tag:"BOWL2"},
{name:"Avesh Khan", role:"PACE", rating:8.1, foreign:false, tag:"BOWL1"},
{name:"Jaydev Unadkat", role:"PACE", rating:8.1, foreign:false, tag:"BOWL1"},
{name:"Akash Deep", role:"PACE", rating:8.1, foreign:false, tag:"BOWL2"},
{name:"Vijaykumar Vyshak", role:"PACE", rating:8.0, foreign:false, tag:"BOWL2"},
{name:"Umesh Yadav", role:"PACE", rating:7.9, foreign:false, tag:"BOWL1"},
{name:"Umran Malik", role:"PACE", rating:7.9, foreign:false, tag:"BOWL1"},
{name:"Shivam Mavi", role:"PACE", rating:7.9, foreign:false, tag:"BOWL1"},
{name:"Mayank Yadav", role:"PACE", rating:7.8, foreign:false, tag:"BOWL2"},
{name:"Yash Thakur", role:"PACE", rating:7.8, foreign:false, tag:"BOWL2"},
{name:"Rasikh Salam", role:"PACE", rating:7.8, foreign:false, tag:"BOWL2"},
{name:"Simarjeet Singh", role:"PACE", rating:7.8, foreign:false, tag:"BOWL2"},
{name:"Anshul Kamboj", role:"PACE", rating:7.8, foreign:false, tag:"BOWL2"},
{name:"Kuldeep Sen", role:"PACE", rating:7.8, foreign:false, tag:"BOWL2"},
{name:"Kartik Tyagi", role:"PACE", rating:7.7, foreign:false, tag:"BOWL2"},
{name:"Mukesh Choudhary", role:"PACE", rating:7.7, foreign:false, tag:"BOWL2"},
{name:"Sandeep Warrier", role:"PACE", rating:7.5, foreign:false, tag:"BOWL1"},
{name:"Navdeep Saini", role:"PACE", rating:7.3, foreign:false, tag:"BOWL1"},
{name:"Chetan Sakariya", role:"PACE", rating:7.0, foreign:false, tag:"BOWL1"},
{name:"Arjun Tendulkar", role:"PACE", rating:6.0, foreign:false, tag:"BOWL2"},

/* ============================================================ */
/* SPIN BOWLERS                          */
/* ============================================================ */

/* --- Indian Spin Bowlers --- */
{name:"Varun Chakravarthy", role:"SPIN", rating:9.6, foreign:false, tag:"BOWL1"},
{name:"Kuldeep Yadav", role:"SPIN", rating:9.5, foreign:false, tag:"BOWL1"},
{name:"Yuzvendra Chahal", role:"SPIN", rating:9.4, foreign:false, tag:"BOWL1"},
{name:"Ravi Bishnoi", role:"SPIN", rating:8.8, foreign:false, tag:"BOWL1"},
{name:"R Sai Kishore", role:"SPIN", rating:8.6, foreign:false, tag:"BOWL2"},
{name:"Suyash Sharma", role:"SPIN", rating:8.4, foreign:false, tag:"BOWL2"},
{name:"Digvesh Rathi", role:"SPIN", rating:8.3, foreign:false, tag:"BOWL2"},
{name:"Rahul Chahar", role:"SPIN", rating:8.2, foreign:false, tag:"BOWL1"},
{name:"Mayank Markande", role:"SPIN", rating:7.9, foreign:false, tag:"BOWL1"},
{name:"Vignesh Puthur", role:"SPIN", rating:7.9, foreign:false, tag:"BOWL2"},
{name:"Karn Sharma", role:"SPIN", rating:7.7, foreign:false, tag:"BOWL1"},
{name:"Piyush Chawla", role:"SPIN", rating:7.4, foreign:false, tag:"BOWL1"},
{name:"Shreyas Gopal", role:"SPIN", rating:7.0, foreign:false, tag:"BOWL1"},
{name:"Murugan Ashwin", role:"SPIN", rating:6.9, foreign:false, tag:"BOWL1"},
{name:"Tanush Kotian", role:"SPIN", rating:6.8, foreign:false, tag:"BOWL2"},
{name:"Manav Suthar", role:"SPIN", rating:6.7, foreign:false, tag:"BOWL2"},

/* --- Overseas Spin Bowlers --- */
{name:"Rashid Khan", role:"SPIN", rating:9.7, foreign:true, tag:"M"},
{name:"Noor Ahmad", role:"SPIN", rating:9.2, foreign:true, tag:"BOWL1"},
{name:"Adam Zampa", role:"SPIN", rating:8.9, foreign:true, tag:"BOWL1"},
{name:"Maheesh Theekshana", role:"SPIN", rating:8.6, foreign:true, tag:"BOWL1"},
{name:"Wanindu Hasaranga", role:"SPIN", rating:8.6, foreign:true, tag:"BOWL1"},
{name:"Mujeeb Ur Rahman", role:"SPIN", rating:8.5, foreign:true, tag:"BOWL1"},
{name:"Keshav Maharaj", role:"SPIN", rating:7.8, foreign:true, tag:"BOWL1"},
{name:"Adil Rashid", role:"SPIN", rating:7.8, foreign:true, tag:"BOWL1"},
{name:"Tabraiz Shamsi", role:"SPIN", rating:7.7, foreign:true, tag:"BOWL1"},
{name:"Allah Ghazanfar", role:"SPIN", rating:7.6, foreign:true, tag:"BOWL2"},
{name:"Akeal Hosein", role:"SPIN", rating:7.5, foreign:true, tag:"BOWL1"},
{name:"Ish Sodhi", role:"SPIN", rating:7.4, foreign:true, tag:"BOWL1"},
{name:"Vijayakanth Viyaskanth", role:"SPIN", rating:7.1, foreign:true, tag:"BOWL2"}

];
